#!/usr/bin/env python3
"""Verify the largest GF(5) repeated box used in the manuscript."""

import argparse
import hashlib
import json
from pathlib import Path

from check_gf13_repeated_lineage import (
    certify_matrix, kim_reduction, row_space_equal, tuple_tex,
)
from universal_display import (
    kim_build, matrix_small_tex, matrix_tex, permute_vector,
    universal_normalize,
)


HERE = Path(__file__).resolve().parent
REPOSITORY = (
    "https://github.com/LeGenAI/intersection-coding-theory-cohomology/"
    "blob/afm-revision-2026-08-27/"
    "Formalization/Verification/Examples/certificates/gf5-repeated-top.json"
)


def source_matrix(right, p):
    k = len(right)
    return [[2 * int(i == j) % p for j in range(k)] + right[i]
            for i in range(k)]


def build_outputs():
    source_bytes = (HERE / "gf5_repeated_top.json").read_bytes()
    source = json.loads(source_bytes)
    p, c = source["field_order"], source["square_root_minus_one"]
    g24 = source_matrix(source["source"]["right_matrix"], p)
    c24 = certify_matrix(g24, p, source["source"]["parameters"])
    c24["a_d"] = source["source"]["a_d"]
    c24["minimum_weight_verified_by_magma"] = True

    reduction = source["reduction"]
    pair = [value - 1 for value in reduction["ordered_pair_one_based"]]
    step = kim_reduction(g24, pair, c, p)
    g22 = reduction["parent_generator"]
    if not row_space_equal(step["parent_matrix"], g22, p):
        raise ValueError("stored GF(5) parent row space")
    c22 = certify_matrix(g22, p, reduction["parent_parameters"],
                         reduction["parent_weight_distribution"])

    # This deterministic pairing admits the literal Corollary 3.10
    # normalization. Entries are Kim-parent coordinates, not child coordinates.
    parent_pairs_one_based = [
        (22, 8), (9, 13), (5, 12), (19, 18), (10, 17), (11, 16),
        (6, 4), (2, 3), (20, 14), (1, 15), (21, 7),
    ]
    parent_pairs = [(a - 1, b - 1) for a, b in parent_pairs_one_based]
    display_parent = universal_normalize(
        step["parent_matrix"], parent_pairs, c, p,
        rank_one_split_normalize=True)
    display_x = permute_vector(
        step["x"], display_parent["coordinate_order_zero_based"])
    display_child = kim_build(display_parent["matrix"], display_x, c, p)
    child_order = [1, 0] + [2 + j for j in
                            display_parent["coordinate_order_zero_based"]]
    if not row_space_equal(
            display_child,
            [[row[j] for j in child_order]
             for row in step["child_kim_matrix"]], p):
        raise ValueError("GF(5) child with universal parent")
    display = {
        "parent": display_parent, "correction": display_x,
        "child_matrix": display_child,
        "new_pair_oriented_as_01": True,
        "child_row_space_verified": True,
    }

    certificate = {
        "schema_version": 1,
        "artifact_id": "GF5-REPEATED-22-24",
        "source_sha256": hashlib.sha256(source_bytes).hexdigest(),
        "interpretation": (
            "Exact largest repeated-box edge from a self-dual [22,11,8] "
            "parent to the Georgiou--Koukouvinos [24,12,9] endpoint."
        ),
        "levels_ascending": [c22, c24],
        "step": step,
        "largest_universal_display": display,
        "magma_audit": {
            **source["magma_audit"],
            "replay": "Formalization/Verification/Examples/gf5_repeated_top.m",
            "receipt": "Formalization/Verification/Examples/gf5_repeated_top.receipt.txt",
        },
    }
    results = {
        "input_sha256": certificate["source_sha256"],
        "method": "exact rank/Gram/row-space/Kim--Lee reconstruction; parent distribution checked by MacWilliams",
        "certificate": certificate,
    }

    rows = (
        r"0 & $C_{22}^{(5)}$ & $[22,11,8]$ & 660 & base parent \\"
        "\n"
        r"1 & $C_{24}^{(5)}$ & $[24,12,9]$ & $\mathbf{1,056}$ & "
        r"$\mathcal B_2(G_{22}^{(5)},x_{22}^{(5)})$ \\"
    )
    catalogue = (
        r"\href{" + REPOSITORY + r"}{$C_{24}^{(5)}$} & 5 & "
        r"$[24,12,9];\,\mathbf{1,056}$ & $(9;\,1,056)$ & "
        r"Georgiou--Koukouvinos \\"
    )
    tex = "% Generated by check_gf5_repeated_top.py; do not edit.\n"
    tex += "\\newcommand{\\GFFiveRepeatedLineageRows}{%\n" + rows + "\n}\n"
    tex += "\\newcommand{\\GFFiveRepeatedCatalogueRows}{%\n" + catalogue + "\n}\n"
    tex += ("\\newcommand{\\GFFiveLargestRepeatedMatrix}{"
            + matrix_tex(display_child, display_parent["k"],
                         display_parent["r"], split_corollary=True) + "}\n")
    tex += ("\\newcommand{\\GFFiveLargestParentParameters}"
            f"{{c={c},\\; k={display_parent['k']},\\; "
            f"r={display_parent['r']},\\; "
            f"D={matrix_small_tex(display_parent['D'])}}}\n")
    tex += ("\\newcommand{\\GFFiveTwentyTwoCorrection}{"
            + tuple_tex(display_x) + "}\n")
    tex += ("\\newcommand{\\GFFiveRepeatedCertificate}{\\href{" + REPOSITORY
            + "}{$C_{24}^{(5)}$}}\n")
    return {
        "gf5_repeated_top_results.json": json.dumps(results, indent=2) + "\n",
        "gf5_repeated_top_data.tex": tex,
        "certificates/gf5-repeated-top.json":
            json.dumps(certificate, indent=2) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for relative_name, contents in build_outputs().items():
        path = HERE / relative_name
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
        elif not path.exists() or path.read_text() != contents:
            raise SystemExit(f"stale generated file: {relative_name}")
    print("PASS GF(5) largest repeated box: [22,11,8] -> [24,12,9]")


if __name__ == "__main__":
    main()
