#!/usr/bin/env python3
"""Verify the largest GF(5) repeated box used in the manuscript."""

import argparse
import hashlib
import json
from pathlib import Path

from check_gf13_repeated_lineage import (
    certify_matrix, kim_reduction, row_space_equal, tuple_tex,
)


HERE = Path(__file__).resolve().parent
REPOSITORY = (
    "https://github.com/LeGenAI/intersection-coding-theory-cohomology/"
    "blob/afm-revision-2026-08-27/"
    "Formalization/Verification/Examples/certificates/gf5-repeated-top.json"
)


def source_matrix(right, p):
    k = len(right)
    return [[2 * int(i == j) % p for j in range(k)] + right[i]
            for i in range(k)]


def build_outputs():
    source_bytes = (HERE / "gf5_repeated_top.json").read_bytes()
    source = json.loads(source_bytes)
    p, c = source["field_order"], source["square_root_minus_one"]
    g24 = source_matrix(source["source"]["right_matrix"], p)
    c24 = certify_matrix(g24, p, source["source"]["parameters"])
    c24["a_d"] = source["source"]["a_d"]
    c24["minimum_weight_verified_by_magma"] = True

    reduction = source["reduction"]
    pair = [value - 1 for value in reduction["ordered_pair_one_based"]]
    step = kim_reduction(g24, pair, c, p)
    g22 = reduction["parent_generator"]
    if not row_space_equal(step["parent_matrix"], g22, p):
        raise ValueError("stored GF(5) parent row space")
    c22 = certify_matrix(g22, p, reduction["parent_parameters"],
                         reduction["parent_weight_distribution"])

    certificate = {
        "schema_version": 1,
        "artifact_id": "GF5-REPEATED-22-24",
        "source_sha256": hashlib.sha256(source_bytes).hexdigest(),
        "interpretation": (
            "Exact largest repeated-box edge from a self-dual [22,11,8] "
            "parent to the Georgiou--Koukouvinos [24,12,9] endpoint."
        ),
        "levels_ascending": [c22, c24],
        "step": step,
        "magma_audit": {
            **source["magma_audit"],
            "replay": "Formalization/Verification/Examples/gf5_repeated_top.m",
            "receipt": "Formalization/Verification/Examples/gf5_repeated_top.receipt.txt",
        },
    }
    results = {
        "input_sha256": certificate["source_sha256"],
        "method": "exact rank/Gram/row-space/Kim--Lee reconstruction; parent distribution checked by MacWilliams",
        "certificate": certificate,
    }

    rows = (
        r"0 & $C_{22}^{(5)}$ & $[22,11,8]$ & 660 & base parent \\"
        "\n"
        r"1 & $C_{24}^{(5)}$ & $[24,12,9]$ & 1,056 & "
        r"$\mathcal B_2(G_{22}^{(5)},x_{22}^{(5)})$ \\"
    )
    catalogue = (
        r"\href{" + REPOSITORY + r"}{\texttt{GF5-R24}} & 5 & "
        r"$[24,12,9];\,1,056$ & $(9;\,1,056)$ & "
        r"Georgiou--Koukouvinos \\"
    )
    tex = "% Generated by check_gf5_repeated_top.py; do not edit.\n"
    tex += "\\newcommand{\\GFFiveRepeatedLineageRows}{%\n" + rows + "\n}\n"
    tex += "\\newcommand{\\GFFiveRepeatedCatalogueRows}{%\n" + catalogue + "\n}\n"
    tex += ("\\newcommand{\\GFFiveTwentyTwoCorrection}{"
            + tuple_tex(step["x"]) + "}\n")
    tex += ("\\newcommand{\\GFFiveRepeatedCertificate}{\\href{" + REPOSITORY
            + "}{\\texttt{GF5-REPEATED-22-24}}}\n")
    return {
        "gf5_repeated_top_results.json": json.dumps(results, indent=2) + "\n",
        "gf5_repeated_top_data.tex": tex,
        "certificates/gf5-repeated-top.json":
            json.dumps(certificate, indent=2) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for relative_name, contents in build_outputs().items():
        path = HERE / relative_name
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
        elif not path.exists() or path.read_text() != contents:
            raise SystemExit(f"stale generated file: {relative_name}")
    print("PASS GF(5) largest repeated box: [22,11,8] -> [24,12,9]")


if __name__ == "__main__":
    main()
