import Formalization.Components.QaryRankOneUniversalPairing

open BuildingUpFormalization.Components.QaryRankOneUniversalPairing

#print axioms frontPrepended_readSuccessor_eq_rankBoxedRowSpace_exact
#print axioms frontPrepended_readSuccessor_eq_relabel_flattenRows_exact
#print axioms repeated_step_has_rankOne_orientedPairing_exact
#print axioms repeated_step_front_has_rankOne_orientedPairing_exact
#print axioms rankBoxed_flatten_has_rankOne_orientedPairing_exact
#print axioms every_qary_selfDualCode_has_rankOne_orientedPairing_exact
