import Formalization.Components.RepeatedBoxConverse

open BuildingUpFormalization.Components.RepeatedBox

#print axioms extension_dictionary_exact
#print axioms extension_zero_column_iff
#print axioms repeated_step_selfDual_exact
#print axioms repeated_step_normalization_exact
#print axioms repeated_step_kim_lee_iff
#print axioms repeated_step_rowSpace_dichotomy_exact
#print axioms paper_rankBoxed_head_step_kim_lee_iff
#print axioms determined_repeated_step_kim_lee_iff
#print axioms kim_lee_to_repeated_exact
